/*******************************************************************************
 *   
 *   Copyright 2007 Mytech Ingenieria Aplicada <http://www.mytechia.com>, Gervasio Varela
 * 
 *   This file is part of Mytechia Commons.
 *
 *   Mytechia Commons is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Lesser General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   Mytechia Commons is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public License
 *   along with Mytechia Commons.  If not, see <http://www.gnu.org/licenses/>.
 * 
 ******************************************************************************/

package com.mytechia.commons.framework.modelaction.action.undoable;

import com.mytechia.commons.framework.modelaction.action.changeaction.ChangeModelAction;
import com.mytechia.commons.framework.modelaction.changesmanager.ChangesManager;
import javax.swing.undo.UndoableEdit;
import javax.swing.undo.UndoableEditSupport;


/** This class should be extended by all classes that 
 * implement undoable model operations. It uses  a Template Method pattern
 * to automatically "post" UndoableEdit objects in the undo support subsystem.
 *
 * An <code>UndoableEditSupport</code> object is needed to post the
 * <code>UndoableEdit</code> objects generated by the actions to undo/redo operations.
 *
 * The class has a protected field of the AbstractUndoableEdit. In case that
 * the operation needs to suppor do/redo, the implementation of the <code>executeUndoableOp</code>
 * method should initialize this field with the apropieante UndoableEdit object
 * to use in the undo/redo operations.
 *
 * @author  Gervasio Varela Fernandez
 * @version 1
 *
 * File: UndoableModelAction.java
 * Date: 27 de noviembre de 2007
 * Changelog:
 *
 *      27 de noviembre de 2007  --  Initial version
 */
public abstract class UndoableModelAction extends ChangeModelAction
{
    
    
    private UndoableEditSupport undoSupport = null;
    protected UndoableEdit undoableEdit = null;
    
    
    public UndoableModelAction(String name, 
            UndoableEditSupport undoSupport, ChangesManager changesManager)
    {
        super(name, changesManager);
        this.undoSupport = undoSupport;
    }
    
    
    public final Object executeChange() throws Exception
    {
        
        Object ret = executeUndoableOp();
        
        if ((undoableEdit != null) && (undoSupport != null))
            undoSupport.postEdit(undoableEdit);
        
        return ret;
        
    }
    
    
    protected abstract Object executeUndoableOp() throws Exception;
    
    
}
